version: "3.5"
services:

    redis:
      image: redis:alpine
      container_name: php-redis

    mysql:
      image: mysql:5.7
      container_name: php-mysql
      volumes:
        - "./database:/var/lib/mysql"
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: php-webserver
      volumes:
          - ../infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ${SYMFONY_APP_PATH}:/application
      ports:
       - "8080:80"

    php-fpm:
      build: php-fpm
      container_name: php-fpm
      volumes:
        - ${SYMFONY_APP_PATH}:/application
        - ../infrastructure/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/infrastructure-overrides.ini
        - ./var:/application/var
        - ../application:/application
      links:
        - mysql:php-mysql
      environment:
        XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST} remote_enable=${XDEBUG_REMOTE_ENABLE}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8081:80"
        environment:
            - PMA_USER=${MYSQL_USER}
            - PMA_PASSWORD=${MYSQL_PASSWORD}
            - PMA_HOST=php-mysql
        links:
            - mysql:php-mysql
